[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mangograd"
version = "0.1.0"
description = "A transparent, pure Python autograd engine born out of Andrej Karpathy's micrograd."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "graphviz",
    "numpy"
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mangograd*"]
